import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import { ThemeProvider } from 'styled-components';

import theme from '@/global/theme';

import StyledComponentsRegistry from './registry';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_br">
      <body className={raleway.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
